Update dockerfile-test5

diff --git a/docker/dockerfile b/docker/dockerfile
--- a/docker/dockerfile
+++ b/docker/dockerfile
@@ -111,6 +111,6 @@ RUN chmod +x /app/extra/upload-github-release-asset.sh
 # Dist only
 RUN ls -l /app
 RUN pwd
-RUN cd /app && tar -zcvf $DIST dist
+RUN cd /app && [ -d dist ] && tar -zcvf $DIST dist || echo "dist directory not found, skipping tar"
 RUN /app/extra/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=louislam repo=uptime-kuma tag=$VERSION filename=/app/$DIST
 
