Update dockerfile: removed release

diff --git a/docker/dockerfile b/docker/dockerfile
--- a/docker/dockerfile
+++ b/docker/dockerfile
@@ -109,8 +109,8 @@ RUN chmod +x /app/extra/upload-github-release-asset.sh
 # RUN /app/extra/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=louislam repo=uptime-kuma tag=$VERSION filename=$FILE
 
 # Dist only
-RUN ls -l /app
-RUN pwd
-RUN cd /app && [ -d dist ] && tar -zcvf $DIST dist || echo "dist directory not found, skipping tar"
-RUN /app/extra/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=louislam repo=uptime-kuma tag=$VERSION filename=/app/$DIST
+# RUN ls -l /app
+# RUN pwd
+# RUN cd /app && [ -d dist ] && tar -zcvf $DIST dist || echo "dist directory not found, skipping tar"
+# RUN /app/extra/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=louislam repo=uptime-kuma tag=$VERSION filename=/app/$DIST
 
